spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:/db/migration
  cache:
    type: redis
    redis:
      time-to-live: 60s
  redis:
    host: 127.0.0.1
    port: 6379

cache:
  subway:
    lines:
      name: lines
      ttl: 600
    line:
      name: line
      ttl: 300
    line-responses:
      name: line-responses
      ttl: 600
    line-response:
      name: line-response
      ttl: 300
    stations:
      name: stations
      ttl: 300
    find-path:
      name: find-path
      ttl: 3600

handlebars:
  suffix: .html
  enabled: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
