spring:
  profiles:
    active: local
  cache:
    type: redis
    redis:
      time-to-live: 60s
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 512

cache:
  subway:
    lines:
      name: lines
      ttl: 600
    line:
      name: line
      ttl: 300
    line-responses:
      name: line-responses
      ttl: 600
    line-response:
      name: line-response
      ttl: 300
    stations:
      name: stations
      ttl: 300
    find-path:
      name: find-path
      ttl: 3600

handlebars:
  suffix: .html
  enabled: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org:.springframework.cache: trace

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      master:
        username: subway
        password: subway_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/subway
      slave:
        username: subway
        password: subway_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/subway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
        format_sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:/db/migration
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      master:
        username: ${MYSQL_MASTER_USERNAME:subway}
        password: ${MYSQL_MASTER_PASSWORD:subway_password}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_MASTER_HOST:172.17.0.1}:${MYSQL_MASTER_PORT:3306}/${MYSQL_MASTER_DATABASE:subway}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      slave:
        username: ${MYSQL_SLAVE_USERNAME:subway}
        password: ${MYSQL_SLAVE_PASSWORD:subway_password}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_SLAVE_HOST:172.17.0.1}:${MYSQL_SLAVE_PORT:3307}/${MYSQL_SLAVE_DATABASE:subway}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:/db/migration
  redis:
    host: ${SPRING_REDIS_HOST:172.17.0.1}
    port: ${SPRING_REDIS_PORT:6379}

logback:
  access:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
        format_sql: true
  flyway:
    enabled: false
  redis:
    host: 127.0.0.1
    port: 16379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
